---
- name: Ensure group "www-data" exists
  group:
    name: "www-data"
    state: present

- name: "Add user account for {{ app_user }}"
  user:
    name: "{{ app_user }}"
    shell: "/bin/bash"
    groups: "www-data"
    append: yes

- name: "Create .ssh directory for {{ app_user }}"
  file:
    path: "~{{ app_user }}/.ssh"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0700

- name: Add authorized keys for {{ app_user }}
  copy:
    content: "{{ (authorized_keys[app_user] + additional_authorized_keys[app_user]) | join('\n') }}"
    dest: "~{{ app_user }}/.ssh/authorized_keys"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0600
  when: authorized_keys[app_user] is defined

- name: Add private keys for {{ app_user }}
  copy:
    content: "{{ private_keys[app_user] }}"
    dest: "~{{ app_user }}/.ssh/id_rsa"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0600
  when: private_keys[app_user] is defined

- name: Add public keys for {{ app_user }}
  copy:
    content: "{{ public_keys[app_user] }}"
    dest: "~{{ app_user }}/.ssh/id_rsa.pub"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: 0600
  when: public_keys[app_user] is defined
